<?php

namespace Modules\Schemes\Services;

use App\Exceptions\BusinessException;
use Illuminate\Contracts\Pagination\LengthAwarePaginator;
use Illuminate\Support\Str;
use Modules\Schemes\Contracts\Repositories\CourseRepositoryInterface;
use Modules\Schemes\DTOs\CreateCourseDTO;
use Modules\Schemes\DTOs\UpdateCourseDTO;
use Modules\Schemes\Models\Course;

class CourseService
{
    public function __construct(
        private readonly CourseRepositoryInterface $repository
    ) {}

    /**
     * Get paginated list of all courses.
     * Spatie Query Builder reads filter/sort from request automatically.
     */
    public function paginate(int $perPage = 15): LengthAwarePaginator
    {
        return $this->repository->paginate(max(1, $perPage));
    }

    /**
     * List all courses (paginated).
     * Spatie Query Builder reads filter/sort from request automatically.
     */
    public function list(int $perPage = 15): LengthAwarePaginator
    {
        return $this->repository->paginate(max(1, $perPage));
    }

    /**
     * List public (published) courses with pagination.
     * Spatie Query Builder reads filter/sort from request automatically.
     */
    public function listPublic(int $perPage = 15): LengthAwarePaginator
    {
        // For public listing, add status=published automatically
        request()->merge(['filter' => array_merge(request('filter', []), ['status' => 'published'])]);

        return $this->repository->paginate(max(1, $perPage));
    }

    /**
     * Find course by ID.
     */
    public function find(int $id): ?Course
    {
        return $this->repository->findById($id);
    }

    /**
     * Find course by ID or fail.
     */
    public function findOrFail(int $id): Course
    {
        $course = $this->repository->findById($id);
        if (! $course) {
            throw new \Illuminate\Database\Eloquent\ModelNotFoundException;
        }

        return $course;
    }

    /**
     * Find course by slug.
     */
    public function findBySlug(string $slug): ?Course
    {
        return $this->repository->findBySlug($slug);
    }

    /**
     * Create a new course.
     * Note: Slug is auto-generated by HasSlug trait from title.
     */
    public function create(CreateCourseDTO|array $data): Course
    {
        $attributes = $data instanceof CreateCourseDTO ? $data->toArrayWithoutNull() : $data;

        // Remove slug from input - HasSlug trait handles it
        unset($attributes['slug']);

        // Generate code if not provided
        if (! isset($attributes['code'])) {
            $attributes['code'] = $this->generateCourseCode();
        }

        $tags = $attributes['tags'] ?? null;
        unset($attributes['tags']);

        $course = $this->repository->create($attributes);

        if ($tags) {
            $course->tags()->sync($tags);
        }

        return $course->fresh(['tags']);
    }

    /**
     * Update an existing course.
     * Note: Slug is NOT regenerated on update (doNotGenerateSlugsOnUpdate).
     */
    public function update(int $id, UpdateCourseDTO|array $data): Course
    {
        $course = $this->repository->findByIdOrFail($id);
        $attributes = $data instanceof UpdateCourseDTO ? $data->toArrayWithoutNull() : $data;

        // Remove slug from input - HasSlug handles it, and we don't regenerate on update
        unset($attributes['slug']);

        $tags = $attributes['tags'] ?? null;
        unset($attributes['tags']);

        $this->repository->update($course, $attributes);

        if ($tags !== null) {
            $course->tags()->sync($tags);
        }

        return $course->fresh(['tags']);
    }

    /**
     * Delete a course.
     */
    public function delete(int $id): bool
    {
        $course = $this->findOrFail($id);

        return $this->repository->delete($course);
    }

    /**
     * Publish a course.
     *
     * @throws BusinessException
     */
    public function publish(int $id): Course
    {
        $course = $this->findOrFail($id);

        // Business rule: course must have at least one unit with lessons
        if ($course->units()->count() === 0) {
            throw new BusinessException(
                'Kursus tidak dapat dipublikasikan karena belum memiliki unit.',
                ['units' => ['Kursus harus memiliki minimal satu unit.']]
            );
        }

        $hasLessons = $course->units()->whereHas('lessons')->exists();
        if (! $hasLessons) {
            throw new BusinessException(
                'Kursus tidak dapat dipublikasikan karena belum memiliki lesson.',
                ['lessons' => ['Kursus harus memiliki minimal satu lesson.']]
            );
        }

        $this->repository->update($course, [
            'status' => 'published',
            'published_at' => now(),
        ]);

        return $course->fresh();
    }

    /**
     * Unpublish a course.
     */
    public function unpublish(int $id): Course
    {
        $course = $this->repository->findByIdOrFail($id);

        $this->repository->update($course, [
            'status' => 'draft',
            'published_at' => null,
        ]);

        return $course->fresh();
    }

    /**
     * Generate a unique course code.
     */
    private function generateCourseCode(): string
    {
        do {
            $code = 'CRS-'.strtoupper(Str::random(6));
        } while (Course::where('code', $code)->exists());

        return $code;
    }
}
